QUERY_SELECT_ALL_USERS = 'SELECT * FROM users'
QUERY_SELECT_USER_BY_UUID = 'SELECT * FROM users WHERE uuid = "{0}"'
QUERY_SELECT_USER_BY_TOKEN = 'SELECT * FROM users WHERE token = "{0}"'
QUERY_SELECT_USER_BY_EMAIL = 'SELECT * FROM users WHERE email = "{0}"'
QUERY_DELETE_USER_BY_UUID = 'DELETE FROM users where uuid = "{0}"'
QUERY_INSERT_USER = 'INSERT INTO users VALUES ("{0}", "{1}", "{2}", "{3}", "{4}", "{5}", "{6}")'
QUERY_UPDATE_USER = 'UPDATE users SET email = "{0}", firstname = "{1}", lastname = "{2}", password = "{3}" , token = "{4}" WHERE uuid = "{5}"'
QUERY_UPDATE_TOKEN_BY_EMAIL = 'UPDATE users SET token = "{0}" WHERE email = "{1}"'
